services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASS: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_network
    volumes:
      - postgres:/data/postgres

    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: mail-dev/mail-dev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local